let e = module.exports = {
    API_URL: 'https://discordapp.com/api',
    CDN_URL: 'https://cdn.discordapp.com',
    WS_URL: 'wss://gateway.discord.gg',
    Endpoints: {
        Gateway: (v)=>`${e.WS_URL}/?v=${v}`,
        Channel: (cid) => `${e.API_URL}/channels/${cid}`,
        Messages: (cid) => `${e.API_URL}/channels/${cid}/messages`,
        Message: (cid, mid) => `${e.API_URL}/channels/${cid}/messages/${mid}`,
        BulkDeleteMessages: (cid) => `${e.API_URL}/channels/${cid}/message/bulk_delete`,
        PermissionsOverwrite: (cid, oid) => `${e.API_URL}/channels/${cid}/permissions/${oid}`,
        Invites: (cid) => `${e.API_URL}/channels/${cid}/invites`,
        Invite: (iid) => `${e.API_URL}/invites/${iid}`,
        Typing: (cid) => `${e.API_URL}/channels/${cid}/typing`,
        Pins: (cid) => `${e.API_URL}/channels/${cid}/pins`,
        Pinned: (cid, mid) => `${e.API_URL}/channels/${cid}/pins/${mid}`,
        GroupDMMember: (cid, uid) => `v/channels/${cid}/recipients/${uid}`,
        Guilds: () => `${e.API_URL}/guilds`,
        Guild: (gid) => `${e.API_URL}/guilds/${gid}`,
        GuildChannels: (gid) => `${e.API_URL}/guilds/${gid}/channels`,
        Members: (gid) => `${e.API_URL}/guilds/${gid}/members`,
        Member: (gid, uid) => `${e.API_URL}/guilds/${gid}/members/${uid}`,
        Bans: (gid) => `${e.API_URL}/guilds/${gid}/bans`,
        Ban: (gid, uid) => `${e.API_URL}/guilds/${gid}/bans/${uid}`,
        Roles: (gid) => `${e.API_URL}/guilds/${gid}/roles`,
        Role: (gid, rid) => `${e.API_URL}/guilds/${gid}/roles/${rid}`,
        Prune: (gid) => `${e.API_URL}/guilds/${gid}/prune`,
        Regions: (gid) => `/${e.API_URL}guilds/${gid}/regions`,
        Integrations: (gid) => `${e.API_URL}/guilds/${gid}/integrations`,
        Integration: (gid, iid) => `${e.API_URL}/guilds/${gid}/integrations/${iid}`,
        IntegrationSync: (gid, iid) => `${e.API_URL}/guilds/${gid}/integrations/${iid}/sync`,
        GuildEmbed: (gid) => `${e.API_URL}/guilds/${gid}/embed`,
        BotUser: () => `${e.API_URL}/users/@me`,
        User: (uid) => `${e.API_URL}/users/${uid}`,
        BotGuilds: () => `${e.API_URL}/users/@me/guilds`,
        BotGuild: (gid) => `${e.API_URL}/users/@me/guilds/${gid}`,
        BotDMs: () => `${e.API_URL}/users/@me/channels`,
        BotConnections: () => `${e.API_URL}/users/@me/connections`,
        VoiceRegions: () => `${e.API_URL}/voice/regions`,
    },
    CDN: {
        Avatar: (uid, ah) => `${e.CDN_URL}/avatars/${uid}/${ah}.jpg`,
        GuildIcon: (gid, ih) => `${e.CDN_URL}/icons/${gid}/${ih}.jpg`,
        AppIcon: (aid, ih) => `${e.CDN_URL}/icons/${aid}/${ih}.jpg`,
    }
}